spring:
    datasource:
        url: jdbc:mysql://prodserver:3306/HRMS
        username: root
        password: Cmcuni@2025
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
mybatis:
    type-aliases-package: com.example.hrms.biz.main.booking.model,
                          com.example.hrms.biz.main.department.model,
                          com.example.hrms.biz.main.meetingroom.model,
                          com.example.hrms.biz.main.request.model,
                          com.example.hrms.biz.main.role.model,
                          com.example.hrms.biz.main.user.model