spring:
    datasource:
        url: jdbc:mysql://devserver:3306/HRMS
        username: root
        password: Trungdu@2004
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
        root: DEBUG
mybatis:
    type-aliases-package: com.example.hrms.biz.main.booking.model,
                          com.example.hrms.biz.main.department.model,
                          com.example.hrms.biz.main.meetingroom.model,
                          com.example.hrms.biz.main.request.model,
                          com.example.hrms.biz.main.role.model,
                          com.example.hrms.biz.main.user.model
