spring:
    profiles:
        active: "loc"
    application:
        name: HRMS

server:
    port: 8080
    reactive:
        session:
            cookie:
                http-only: true
                secure: true